### ISSUE TITLE
새로 올라오는 글을 받아보고 싶은데 혹시 RSS 피드 추가 계획이 있으실까요?

### ISSUE THREAD

**Issue by saengmotmi** [MaxKim-J/maxkim-j.github.io#34]
안녕하세요 :) 종혁님께서 쓰시는 글이 좋아서 RSS 리더 앱에 등록해놓고 글이 올라올 때 바로 받아보고 싶은데요.
블로그 코드 상에 RSS 관련 파일이 안보이더라고요. 혹시 제가 못찾고 있는건지, 없다면 혹시 RSS 피드 등록 계획이 있으신지 여쭙고 싶습니다! ㅎㅎ

**Comment by MaxKim-J** [comment]
안녕하세요 종택님! 
RSS 피드는 블로그 만들때부터 해야지 해야지 생각했다가 계속 미뤄졌는데요 🥲 가까운 시일에 시간날 때 한번 붙여보겠습니다.
제 글에 관심 가져주셔서 감사합니다 :)

**Comment by MaxKim-J** [comment]
RSS 피드 추가했습니다!
[https://maxkim-j.github.io/rss.xml](https://t.co/itU0j9zTHW)

**Comment by saengmotmi** [comment]
> RSS 피드 추가했습니다!
> 
> [https://maxkim-j.github.io/rss.xml](https://t.co/itU0j9zTHW) 

헉 감사합니다! 🙇🏻‍♂️
